# Generated by Django 5.0.7 on 2024-07-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('3', '3'), ('2', '2'), ('1', '1')], default='1', max_length=1),
        ),
    ]
