# Generated by Django 5.0.7 on 2024-07-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_tasks_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
